// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPdFYVuaarf4BaUjz83CzTvPfKr4FroQ',
    appId: '1:721209451577:web:4b360aa334eb67acb299e8',
    messagingSenderId: '721209451577',
    projectId: 'project1-96997',
    authDomain: 'project1-96997.firebaseapp.com',
    databaseURL: 'https://project1-96997-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-96997.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSBMa7K2H2vAXqyRva1i3lilKguRPxnAU',
    appId: '1:721209451577:android:3a16d7c7825cc555b299e8',
    messagingSenderId: '721209451577',
    projectId: 'project1-96997',
    databaseURL: 'https://project1-96997-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-96997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfCInf1frVWV8P7-oSa9b-W2-yAbeayg',
    appId: '1:721209451577:ios:d7c982d72004387cb299e8',
    messagingSenderId: '721209451577',
    projectId: 'project1-96997',
    databaseURL: 'https://project1-96997-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-96997.firebasestorage.app',
    iosBundleId: 'com.devvirtuoso.iotSmarthome',
  );
}
